### ISSUE TITLE
Do I doing something wrong? I get this error when i trying to save again after download the image and set it in the view.

### ISSUE THREAD

**Issue by davidramos-om** [zhanziyang/vue-croppa#114]
**This is my code to set a saved image**
![image](https://user-images.githubusercontent.com/1109279/41022598-4612aeec-6927-11e8-9b8f-330bd695182e.png)

its works 👍 :
![image](https://user-images.githubusercontent.com/1109279/41022962-49925b5c-6928-11e8-8cb4-d51d54508590.png)

but problem, this before save :
![image](https://user-images.githubusercontent.com/1109279/41022703-9973231e-6927-11e8-8b72-e3592ba0164c.png)

**Error in this.myCroppa.generateBlob** :
DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at VueComponent.generateBlob (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:40109:19)
    at VueComponent.boundFn [as generateBlob] (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:14775:14)
    at VueComponent._callee4$ (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:27028:31)
    at tryCatch (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:42997:40)
    at Generator.invoke [as _invoke] (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:43231:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:43049:21)
    at step (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:1492:30)
    at http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:1510:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3100/assets/ctrl/vue_main_menu-nav-v1.js:13880:28)

This only append when I use the third method : 
https://zhanziyang.github.io/vue-croppa/#/customization
(Because the others does not works for my, images are being stored in AWS S3

I hope you understand me
thanks

**Comment by zhanziyang** [comment]
Could you try swapping this line:
```js
image.src = ...
```
and this:
```js
image.setAttribute('crossorigin', 'anonymous')
```

Setting "crossorigin" before "src"

**Comment by zhanziyang** [comment]
Cross-origin canvas tainting occurs when the remote image server does not supply proper CORS headers.

This is outside what the component can control, so we're closing the issue. Configure CORS on your image server or proxy the image through your own domain.
